import i18n from "../../i18n";

export const getServicesData = () => {
  const t = i18n.getFixedT(i18n.language);
  return [
    {
      id: "wellness",
      miniHeading: t("services.wellness_mini"),
      mainHeading: t("services.wellness_heading"),
      paragraph: t("services.wellness_para"),
      hasButton: true,
      buttonText: t("services.wellness_btn"),
      mainImage: "/images/services/LE-main.jpeg",
      innerImage: "/images/services/LE-logo.jpeg",
      galleryImages: [
        "/images/services/LE-main.jpeg",
        "/images/services/LE-mini.jpeg",
        "/images/services/LE-3.jpeg",
        "/images/services/LE-4.jpeg",
        "/images/services/LE-5.jpeg",
      ],
      layout: "text-left",
      whatsappNumber: "96566747819",
    },
    {
      id: "marmara",
      miniHeading: t("services.marmara_mini"),
      mainHeading: t("services.marmara_heading"),
      paragraph: t("services.marmara_para"),
      hasButton: true,
      buttonText: t("services.marmara_btn"),
      mainImage: "/images/services/MM-main.jpeg",
      innerImage: "/images/services/MM-logo.jpeg",
      galleryImages: [
        "/images/services/MM-main.jpeg",
        "/images/services/MM-mini.jpeg",
        "/images/services/MM-3.jpeg",
        "/images/services/MM-4.jpeg",
        "/images/services/MM-5.jpeg",
        "/images/services/MM-6.jpeg",
      ],
      layout: "text-right",
      whatsappNumber: "96522207222",
    },
    {
      id: "cafe",
      miniHeading: t("services.chariot_mini"),
      mainHeading: t("services.chariot_heading"),
      paragraph: t("services.chariot_para"),
      hasButton: false,
      mainImage: "/images/services/CH-main.jpeg",
      innerImage: "/images/services/CH-logo.jpeg",
      galleryImages: [
        "/images/services/CH-main.jpeg",
        "/images/services/CH-mini.jpeg",
        "/images/services/CH-3.jpeg",
        "/images/services/CH-4.jpeg",
        "/images/services/CH-5.jpeg",
      ],
      layout: "text-left",
    },
    {
      id: "habka-cafe",
      miniHeading: t("services.habka_mini"),
      mainHeading: t("services.habka_heading"),
      paragraph: t("services.habka_para"),
      hasButton: false,
      mainImage: "/images/services/HB-main.jpeg",
      innerImage: "/images/services/HB-logo.jpeg",
      galleryImages: [
        "/images/services/HB-main.jpeg",
        "/images/services/HB-mini.jpeg",
        "/images/services/HB-3.jpeg",
        "/images/services/HB-4.jpeg",
        "/images/services/HB-5.jpeg",
      ],
      layout: "text-right",
    },
  ];
};