export const servicesData = [
  {
    id: "wellness",
    miniHeading: "Wellness",
    mainHeading: "Indulge in Your Time at Love Ella",
    paragraph:
      "A women's wellness space built around intention. Love Ella offers a curated range of treatments from hair care to skin rituals in an environment that feels like it was made just for you.",
    hasButton: true,
    buttonText: "Book Now",
    mainImage: "/images/services/LE-main.jpeg",
    innerImage: "/images/services/LE-logo.jpeg",
    galleryImages: [
      "/images/services/LE-main.jpeg",
      "/images/services/LE-mini.jpeg",
      "/images/services/LE-3.jpeg",
      "/images/services/LE-5.jpeg",
      "/images/services/LE-4.jpeg",
    ],
    layout: "text-left",
    whatsappNumber: "96566747819",
  },
  {
    id: "marmara",
    miniHeading: "Wellness",
    mainHeading: "Groom & Relax at Marmara",
    paragraph:
      "Refined grooming for the modern man. Marmara is a precise, calm, and considered space where every visit feels like a reset not just a haircut.",
    hasButton: true,
    buttonText: "Book Now",
    mainImage: "/images/services/MM-main.jpeg",
    innerImage: "/images/services/MM-logo.jpeg",
    galleryImages: [
      "/images/services/MM-main.jpeg",
      "/images/services/MM-mini.jpeg",
      "/images/services/MM-3.jpeg",
      "/images/services/MM-4.jpeg",
      "/images/services/MM-5.jpeg",
      "/images/services/MM-6.jpeg",
    ],
    layout: "text-right",
    whatsappNumber: "96522207222",
  },
  {
    id: "cafè",
    miniHeading: "Dining",
    mainHeading: "Elevated Moments at Chariot Café",
    paragraph:
      "A quiet corner where the morning coffee tastes different. Our Chariot Café brings together fresh ingredients, unhurried service, and a view that makes every cup worth savoring.",
    hasButton: false,
    mainImage: "/images/services/CH-main.jpeg",
    innerImage: "/images/services/CH-logo.jpeg",
    galleryImages: [
      "/images/services/CH-main.jpeg",
      "/images/services/CH-mini.jpeg",
      "/images/services/CH-3.jpeg",
      "/images/services/CH-4.jpeg",
      "/images/services/CH-5.jpeg",
    ],
    layout: "text-left",
  },
  {
    id: "habka-cafe",
    miniHeading: "Dining",
    mainHeading: "A Taste of Habka Café",
    paragraph:
      "Rooftop breezes and handcrafted plates. Habka is where the day winds down slowly an open-air experience designed for those who believe the best meals deserve the best views.",
    hasButton: false,
    mainImage: "/images/services/HB-main.jpeg",
    innerImage: "/images/services/HB-logo.jpeg",
    galleryImages: [
      "/images/services/HB-main.jpeg",
      "/images/services/HB-mini.jpeg",
      "/images/services/HB-3.jpeg",
      "/images/services/HB-4.jpeg",
      "/images/services/HB-5.jpeg",
    ],
    layout: "text-right",
  },
];
